"""Formula 1, 2026-27 season coverage. The only source of truth for this series.

Data provenance, stated plainly because nothing here may be inferred or estimated:
  - Session dates and times come from sportstimes/f1 (MIT licensed), which publishes every
    session of the current and announced seasons in UTC. No date in this calendar is guessed.
  - Formula 1 has no hand-transcribed file: sportstimes covers it. If a future season appears
    on formula1.com before sportstimes adds it, it goes in data/f1.toml, transcribed BY HAND
    from the official page with a source URL and a read date on every event, and it drops out
    automatically once sportstimes catches up.

Running this writes SCHEDULE.md and f1-2026-27.ics, and prints its integrity checks BEFORE
writing anything.
"""
import datetime as dt
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from racecal import DTSTAMP, SERIES, TERM
from racecal import ics, sources, tz

KEY = "f1"
NAME, PREFIX, SITE, SUFFIX = SERIES[KEY]
HERE = Path(__file__).resolve().parent
ICS = HERE / f"{KEY}-{TERM}.ics"
MD = HERE / "SCHEDULE.md"


def plan():
    """THE planner. verify imports this and re-derives its expectations from it, so a schema
    change cannot leave the check measuring something the build no longer produces."""
    up, seasons = sources.upstream(KEY, PREFIX, SITE, SUFFIX, dt.datetime.now(dt.timezone.utc).year) if SITE else ([], set())
    return up + sources.hand(KEY, PREFIX, seasons)


def integrity(events):
    """(label, ok, detail) for each check. Run and printed before anything is written."""
    uids = [e["uid"] for e in events]
    timed = [e for e in events if not e["allday"]]
    out = [
        ("events present", len(events) > 0, f"{len(events)} events"),
        ("unique UIDs", len(uids) == len(set(uids)), f"{len(set(uids))} distinct of {len(uids)}"),
        ("end after start", all(e["end"] > e["start"] for e in events), "all intervals positive"),
        ("UID shape", all(re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9-]*", u) for u in uids),
         "letters, digits and hyphens only - no spaces, @, :, / or ."),
        ("anchors carry a kind with a lead", all(e["kind"] in ("race", "qualifying", "practice") for e in events),
         f"{sum(e['cls'] == ics.ANCHOR for e in events)} anchors, {sum(e['cls'] == ics.BLOCK for e in events)} blocks"),
        ("practice never marks you busy",
         all(e["cls"] == ics.BLOCK for e in events if e["kind"] == "practice"),
         f"{sum(e['kind'] == 'practice' for e in events)} practice sessions transparent"),
        ("timed sessions are UTC", all(e["start"].tzinfo == dt.timezone.utc for e in timed),
         f"{len(timed)} timed sessions"),
    ]
    return out


def render_md(events):
    lines = [f"# {NAME} - {TERM}", "",
             f"{len(events)} events: practice, qualifying and races. Generated by `build_{KEY}.py`; "
             "do not edit this file by hand.", "",
             "Times below are US Central, converted from the UTC stored in the .ics.", "",
             "| Date | Local time | Session | Venue |", "|---|---|---|---|"]
    for e in sorted(events, key=lambda e: (str(e["start"]), e["uid"])):
        if e["allday"]:
            lines.append(f"| {e['start']:%Y-%m-%d} | all day | {e['summary']} | {e['location']} |")
        else:
            wall, zone = tz.to_central(e["start"])
            lines.append(f"| {wall:%Y-%m-%d} | {wall:%H:%M} {zone} | {e['summary']} | {e['location']} |")
    return "\n".join(lines) + "\n"


def main():
    events = plan()
    failed = 0
    for label, ok, detail in integrity(events):
        print(f"  [{'OK ' if ok else 'FAIL'}] {label}: {detail}")
        failed += not ok
    if failed:
        print(f"{KEY}: {failed} integrity check(s) failed, nothing written")
        return 1
    # Render fully, THEN swap in: a bug mid-render must not have already truncated a good file.
    ics.write_atomic(ICS, ics.calendar(NAME, events, DTSTAMP))
    ics.write_atomic(MD, render_md(events).encode("utf-8"))
    print(f"{KEY}: wrote {ICS.name} and {MD.name}, {len(events)} events")
    return 0


if __name__ == "__main__":
    sys.exit(main())
